// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXaetEdD6OECIW6CH-vXHSRRU49d8hOM',
    appId: '1:376573125112:web:81fd8aac96177f355ef60d',
    messagingSenderId: '376573125112',
    projectId: 'glucolog-a2b42',
    authDomain: 'glucolog-a2b42.firebaseapp.com',
    storageBucket: 'glucolog-a2b42.firebasestorage.app',
    measurementId: 'G-GNFDPGRSTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnYXt0Vz_J0pktacHNqTNmOKA6-lvF_I',
    appId: '1:376573125112:android:daceb319d58b7e035ef60d',
    messagingSenderId: '376573125112',
    projectId: 'glucolog-a2b42',
    storageBucket: 'glucolog-a2b42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL-uZZug7XAvgABG_TZwIp9GS-XiM-xBw',
    appId: '1:376573125112:ios:db53b5082aea513c5ef60d',
    messagingSenderId: '376573125112',
    projectId: 'glucolog-a2b42',
    storageBucket: 'glucolog-a2b42.firebasestorage.app',
    iosBundleId: 'com.example.glucologApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL-uZZug7XAvgABG_TZwIp9GS-XiM-xBw',
    appId: '1:376573125112:ios:db53b5082aea513c5ef60d',
    messagingSenderId: '376573125112',
    projectId: 'glucolog-a2b42',
    storageBucket: 'glucolog-a2b42.firebasestorage.app',
    iosBundleId: 'com.example.glucologApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSXaetEdD6OECIW6CH-vXHSRRU49d8hOM',
    appId: '1:376573125112:web:98274eeced48fff05ef60d',
    messagingSenderId: '376573125112',
    projectId: 'glucolog-a2b42',
    authDomain: 'glucolog-a2b42.firebaseapp.com',
    storageBucket: 'glucolog-a2b42.firebasestorage.app',
    measurementId: 'G-387Y67WF71',
  );
}
